server:
  port: ${PORT:8080}

spring:
  application:
    name: money-manager-backend

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

app:
  cors:
    # Local + Vercel (Default)
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,https://money-manager-frontend-ecru.vercel.app}

  security:
    edit-window-hours: ${EDIT_WINDOW_HOURS:12}

jwt:
  # Must be Base64 (256-bit+)
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
